apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.21.7
    helm:
      releaseName: fluent-bit
      values: |
        logLevel: info

        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 1
                Log_Level debug
                Parsers_File parsers.conf
                Parsers_File custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                Health_Check On
                Trace_Error On

          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*_restauratings_*.log
                multiline.parser docker, cri
                Tag kube.restauratings.*
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On

            [INPUT]
                Name tail
                Path /var/log/containers/ingress-nginx-controller*.log
                multiline.parser docker, cri
                Tag kube.ingress.*
                Mem_Buf_Limit 100MB
                Skip_Long_Lines On

            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter *SYSTEMD*UNIT=kubelet.service
                Read_From_Tail On

          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                Buffer_Size False
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
                Annotations Off
                Labels On

            [FILTER]
                Name parser
                Match kube.restauratings.*
                Key_Name log
                Parser python_simple
                Reserve_Data On
                Preserve_Key On

            [FILTER]
                Name parser
                Match kube.restauratings.*
                Key_Name message
                Parser http_extractor
                Reserve_Data On
                Preserve_Key On

            [FILTER]
                Name parser
                Match kube.restauratings.*
                Key_Name log
                Parser mongodb_json
                Reserve_Data On
                Preserve_Key On

            [FILTER]
                Name parser
                Match kube.ingress.*
                Key_Name log
                Parser nginx_custom
                Reserve_Data On

            [FILTER]
                Name record_modifier
                Match kube.restauratings.*
                Record app_type restauratings

            [FILTER]
                Name parser
                Match kube.restauratings.*
                Key_Name log
                Parser log_level_extractor
                Reserve_Data On
                Preserve_Key On

          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Index fluent-bit
                Type _doc
                Host elasticsearch.logging.svc
                Port 9200
                tls Off
                Logstash_Format On
                Logstash_Prefix logstash
                Retry_Limit False
                Suppress_Type_Name On

            [OUTPUT]
                Name es
                Match host.*
                Index fluent-bit
                Type _doc
                Host elasticsearch.logging.svc
                Port 9200
                tls Off
                Logstash_Format On
                Logstash_Prefix node
                Retry_Limit False
                Suppress_Type_Name On

          customParsers: |
            [PARSER]
                Name python_simple
                Format regex
                Regex ^\[(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\] (?<log_level>\w+) in (?<module>\w+): (?<message>.*)$
                Time_Key timestamp
                Time_Format %Y-%m-%d %H:%M:%S,%L

            [PARSER]
                Name http_extractor
                Format regex
                Regex (?<http_method>GET|POST|PUT|DELETE|PATCH) (?<http_url>http://[^\s]+) - (?<http_status>\d{3})

            [PARSER]
                Name mongodb_json
                Format json
                Time_Key t.$date
                Time_Format %Y-%m-%dT%H:%M:%S.%LZ

            [PARSER]
                Name log_level_extractor
                Format regex
                Regex .*(?<extracted_level>ERROR|WARN|WARNING|INFO|DEBUG).*

            [PARSER]
                Name nginx_custom
                Format regex
                Regex ^(?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<host>[^ ]*) (?<server_protocol>[^ ]*)
                Time_Key time
                Time_Format %d/%b/%Y:%H:%M:%S %z

            [PARSER]
                Name json_parser
                Format json
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%NZ

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true