apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restauratings-umbrella
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
spec:
  project: default
  source:
    repoURL: git@gitlab.com:greengo-jenkins/restauratings-gitops.git
    path: umbrella-chart
    targetRevision: HEAD
    helm:
  destination:
    server: https://kubernetes.default.svc
    namespace: restauratings
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true