apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.16.1
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller
        
        controller:
          create: true
          
        service:
          type: ClusterIP
          port: 8080
          
        rbac:
          create: true
          
        serviceAccount:
          create: true
          name: sealed-secrets-controller
          
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
            
        nodeSelector: {}
        tolerations: []
        affinity: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true